#!/usr/bin/env python3
"""
Script to plot Unitree motor data from CSV files generated by the low level interface.

Usage:
    python plot_unitree.py [--data=/path/to/folder] [--start-time=5.0] [--end-time=30.0]
    
If no data path is provided, uses the most recent folder from unitree_logs.
"""

import argparse
import csv
import glob
import os
import sys
from pathlib import Path
from typing import Optional, Tuple, List, Dict

import matplotlib.pyplot as plt
import numpy as np


def find_most_recent_unitree_folder() -> Optional[str]:
    """Find the most recent unitree log folder in unitree_logs directory."""
    # Get ROBOT_RL_ROOT from environment
    robot_rl_root = os.environ.get("ROBOT_RL_ROOT", "")
    if not robot_rl_root:
        print("Error: ROBOT_RL_ROOT environment variable not set")
        return None
    
    unitree_logs_dir = os.path.join(robot_rl_root, "unitree_logs")
    if not os.path.exists(unitree_logs_dir):
        print(f"Error: unitree_logs directory not found at {unitree_logs_dir}")
        return None
    
    # Find all timestamped subdirectories
    folders = glob.glob(os.path.join(unitree_logs_dir, "*"))
    folders = [f for f in folders if os.path.isdir(f)]
    
    if not folders:
        print(f"Error: No unitree log folders found in {unitree_logs_dir}")
        return None
    
    # Sort by modification time and return most recent
    folders.sort(key=os.path.getmtime, reverse=True)
    most_recent = folders[0]
    print(f"Using most recent folder: {most_recent}")
    return most_recent


def load_joint_names(folder_path: str) -> List[str]:
    """Load joint names from joint_names.txt file."""
    joint_names_path = os.path.join(folder_path, "joint_names.txt")
    joint_names = []
    
    if not os.path.exists(joint_names_path):
        print(f"Warning: joint_names.txt not found in {folder_path}")
        # Return default joint names based on G1 robot
        return [f"joint_{i}" for i in range(28)]  # G1_27DOF + G1_EXTRA_WAIST
    
    try:
        with open(joint_names_path, 'r') as f:
            lines = f.readlines()
            for line in lines[1:]:  # Skip header line
                if ':' in line:
                    parts = line.strip().split(': ')
                    if len(parts) >= 2:
                        joint_names.append(parts[1])
        print(f"Loaded {len(joint_names)} joint names from {joint_names_path}")
    except Exception as e:
        print(f"Error reading joint names file: {e}")
        joint_names = [f"joint_{i}" for i in range(28)]
    
    return joint_names


def load_motor_data(folder_path: str) -> Tuple[np.ndarray, Dict[str, np.ndarray], List[str]]:
    """Load motor data from folder."""
    csv_path = os.path.join(folder_path, "motor_data.csv")
    if not os.path.exists(csv_path):
        raise FileNotFoundError(f"motor_data.csv not found in {folder_path}")
    
    # Load joint names
    joint_names = load_joint_names(folder_path)
    num_joints = len(joint_names)
    
    times = []
    temp1_data = []
    temp2_data = []
    tau_est_data = []
    motorstate_data = []
    
    print(f"Loading data from: {csv_path}")
    
    try:
        with open(csv_path, 'r') as f:
            # Skip comment lines that start with '#'
            while True:
                line = f.readline()
                if not line.startswith('#'):
                    # This is the header line, parse it
                    headers = line.strip().split(',')
                    break
            
            reader = csv.reader(f)
            for row_idx, row in enumerate(reader):
                if len(row) >= 1 + 4 * num_joints:  # timestamp + 4 values per joint
                    time_val = float(row[0])
                    
                    # Parse data for each joint
                    temp1_row = []
                    temp2_row = []
                    tau_est_row = []
                    motorstate_row = []
                    
                    for joint_idx in range(num_joints):
                        base_idx = 1 + joint_idx * 4  # Skip timestamp column
                        temp1_row.append(float(row[base_idx]))
                        temp2_row.append(float(row[base_idx + 1]))
                        tau_est_row.append(float(row[base_idx + 2]))
                        motorstate_row.append(float(row[base_idx + 3]))
                    
                    times.append(time_val)
                    temp1_data.append(temp1_row)
                    temp2_data.append(temp2_row)
                    tau_est_data.append(tau_est_row)
                    motorstate_data.append(motorstate_row)
                        
                if row_idx % 1000 == 0:
                    print(f"Loaded {row_idx} rows...")
                    
    except Exception as e:
        print(f"Error reading CSV file: {e}")
        sys.exit(1)
    
    times = np.array(times)
    motor_data = {
        'temp1': np.array(temp1_data),
        'temp2': np.array(temp2_data), 
        'tau_est': np.array(tau_est_data),
        'motorstate': np.array(motorstate_data)
    }
    
    print(f"Loaded {len(times)} data points spanning {times[-1] - times[0]:.2f} seconds")
    print(f"Data shape: {motor_data['temp1'].shape}")
    
    return times, motor_data, joint_names


def plot_temperatures(times: np.ndarray, motor_data: Dict[str, np.ndarray], 
                     joint_names: List[str], save_dir: str) -> None:
    """Plot motor temperatures."""
    temp1_data = motor_data['temp1']
    temp2_data = motor_data['temp2']
    num_joints = len(joint_names)
    
    # Create subplots - adjust layout based on number of joints
    if num_joints <= 21:
        rows, cols = 5, 6
        figsize = (24, 15)
    else:
        rows, cols = 6, 6
        figsize = (24, 18)
    
    fig, axes = plt.subplots(rows, cols, figsize=figsize)
    fig.suptitle('Motor Temperatures', fontsize=16)
    
    # Flatten axes for easy indexing
    axes_flat = axes.flatten() if isinstance(axes, np.ndarray) else [axes]
    
    for i in range(num_joints):
        ax = axes_flat[i]
        
        # Plot both temperature sensors
        ax.plot(times, temp1_data[:, i], 'r-', linewidth=1, label='Surface', alpha=0.7)
        ax.plot(times, temp2_data[:, i], 'b-', linewidth=1, label='Winding', alpha=0.7)
        
        ax.set_title(f"{joint_names[i]}", fontsize=10)
        ax.set_xlabel('Time (s)')
        ax.set_ylabel('Temperature (°C)')
        ax.grid(True, alpha=0.3)
        ax.legend(fontsize=8)
        
        # Set reasonable temperature limits
        ax.set_ylim([0, 100])
    
    # Hide unused subplots
    for i in range(num_joints, len(axes_flat)):
        axes_flat[i].set_visible(False)
    
    plt.tight_layout()
    
    # Save plot
    output_path = os.path.join(save_dir, 'motor_temperatures.png')
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"Saved motor temperatures plot to: {output_path}")


def plot_torque_estimates(times: np.ndarray, motor_data: Dict[str, np.ndarray], 
                         joint_names: List[str], save_dir: str) -> None:
    """Plot motor torque estimates."""
    tau_est_data = motor_data['tau_est']
    num_joints = len(joint_names)
    
    # Create subplots - adjust layout based on number of joints
    if num_joints <= 21:
        rows, cols = 5, 6
        figsize = (24, 15)
    else:
        rows, cols = 6, 6
        figsize = (24, 18)
    
    fig, axes = plt.subplots(rows, cols, figsize=figsize)
    fig.suptitle('Motor Torque Estimates', fontsize=16)
    
    # Flatten axes for easy indexing
    axes_flat = axes.flatten() if isinstance(axes, np.ndarray) else [axes]
    
    for i in range(num_joints):
        ax = axes_flat[i]
        
        # Plot torque estimate
        ax.plot(times, tau_est_data[:, i], 'g-', linewidth=1)
        
        ax.set_title(f"{joint_names[i]}", fontsize=10)
        ax.set_xlabel('Time (s)')
        ax.set_ylabel('Torque (N⋅m)')
        ax.grid(True, alpha=0.3)
        
        # Add zero line for reference
        ax.axhline(y=0, color='k', linestyle='-', alpha=0.3)
    
    # Hide unused subplots
    for i in range(num_joints, len(axes_flat)):
        axes_flat[i].set_visible(False)
    
    plt.tight_layout()
    
    # Save plot
    output_path = os.path.join(save_dir, 'motor_torques.png')
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"Saved motor torques plot to: {output_path}")


def plot_motor_states(times: np.ndarray, motor_data: Dict[str, np.ndarray], 
                     joint_names: List[str], save_dir: str) -> None:
    """Plot motor states."""
    motorstate_data = motor_data['motorstate']
    num_joints = len(joint_names)
    
    # Create subplots - adjust layout based on number of joints
    if num_joints <= 21:
        rows, cols = 5, 6
        figsize = (24, 15)
    else:
        rows, cols = 6, 6
        figsize = (24, 18)
    
    fig, axes = plt.subplots(rows, cols, figsize=figsize)
    fig.suptitle('Motor States', fontsize=16)
    
    # Flatten axes for easy indexing
    axes_flat = axes.flatten() if isinstance(axes, np.ndarray) else [axes]
    
    for i in range(num_joints):
        ax = axes_flat[i]
        
        # Plot motor state
        ax.plot(times, motorstate_data[:, i], 'purple', linewidth=1)
        
        ax.set_title(f"{joint_names[i]}", fontsize=10)
        ax.set_xlabel('Time (s)')
        ax.set_ylabel('Motor State')
        ax.grid(True, alpha=0.3)
    
    # Hide unused subplots
    for i in range(num_joints, len(axes_flat)):
        axes_flat[i].set_visible(False)
    
    plt.tight_layout()
    
    # Save plot
    output_path = os.path.join(save_dir, 'motor_states.png')
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"Saved motor states plot to: {output_path}")


def plot_temperature_summary(times: np.ndarray, motor_data: Dict[str, np.ndarray], 
                           joint_names: List[str], save_dir: str) -> None:
    """Plot temperature summary statistics."""
    temp1_data = motor_data['temp1']
    temp2_data = motor_data['temp2']
    
    # Calculate statistics
    surface_max = np.max(temp1_data, axis=0)
    surface_mean = np.mean(temp1_data, axis=0)
    winding_max = np.max(temp2_data, axis=0)
    winding_mean = np.mean(temp2_data, axis=0)
    
    # Overall temperature envelope
    temp_max_overall = np.maximum(np.max(temp1_data, axis=1), np.max(temp2_data, axis=1))
    temp_mean_overall = np.mean([np.mean(temp1_data, axis=1), np.mean(temp2_data, axis=1)], axis=0)
    
    fig, axes = plt.subplots(2, 2, figsize=(15, 10))
    fig.suptitle('Motor Temperature Summary (Surface vs Winding)', fontsize=16)
    
    # Joint-wise max temperatures
    joint_indices = np.arange(len(joint_names))
    axes[0, 0].bar(joint_indices - 0.2, surface_max, 0.4, label='Surface Max', alpha=0.7, color='red')
    axes[0, 0].bar(joint_indices + 0.2, winding_max, 0.4, label='Winding Max', alpha=0.7, color='blue')
    axes[0, 0].set_title('Maximum Temperatures by Joint')
    axes[0, 0].set_xlabel('Joint Index')
    axes[0, 0].set_ylabel('Temperature (°C)')
    axes[0, 0].legend()
    axes[0, 0].grid(True, alpha=0.3)
    axes[0, 0].set_xticks(joint_indices[::2])  # Show every other joint for readability
    
    # Joint-wise mean temperatures
    axes[0, 1].bar(joint_indices - 0.2, surface_mean, 0.4, label='Surface Mean', alpha=0.7, color='red')
    axes[0, 1].bar(joint_indices + 0.2, winding_mean, 0.4, label='Winding Mean', alpha=0.7, color='blue')
    axes[0, 1].set_title('Mean Temperatures by Joint')
    axes[0, 1].set_xlabel('Joint Index')
    axes[0, 1].set_ylabel('Temperature (°C)')
    axes[0, 1].legend()
    axes[0, 1].grid(True, alpha=0.3)
    axes[0, 1].set_xticks(joint_indices[::2])
    
    # Overall temperature over time
    axes[1, 0].plot(times, temp_max_overall, 'r-', linewidth=2, label='Max Temp (all joints)')
    axes[1, 0].plot(times, temp_mean_overall, 'b-', linewidth=2, label='Mean Temp (all joints)')
    axes[1, 0].set_title('Overall Temperature Trends')
    axes[1, 0].set_xlabel('Time (s)')
    axes[1, 0].set_ylabel('Temperature (°C)')
    axes[1, 0].legend()
    axes[1, 0].grid(True, alpha=0.3)
    
    # Temperature distribution
    all_temps = np.concatenate([temp1_data.flatten(), temp2_data.flatten()])
    axes[1, 1].hist(all_temps, bins=50, alpha=0.7, color='orange', edgecolor='black')
    axes[1, 1].set_title('Temperature Distribution')
    axes[1, 1].set_xlabel('Temperature (°C)')
    axes[1, 1].set_ylabel('Frequency')
    axes[1, 1].grid(True, alpha=0.3)
    
    plt.tight_layout()
    
    # Save plot
    output_path = os.path.join(save_dir, 'temperature_summary.png')
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"Saved temperature summary plot to: {output_path}")


def main():
    parser = argparse.ArgumentParser(description='Plot Unitree motor data from CSV files')
    parser.add_argument('--data', help='Path to unitree log folder (if not provided, uses most recent)')
    parser.add_argument('--start-time', type=float, default=0.0, help='Start time for plotting (seconds, default: 0.0)')
    parser.add_argument('--end-time', type=float, default=None, help='End time for plotting (seconds, default: None - use all data)')
    args = parser.parse_args()
    
    # Determine folder to use
    if args.data:
        folder_path = args.data
        if not os.path.exists(folder_path):
            print(f"Error: Folder not found: {folder_path}")
            sys.exit(1)
    else:
        folder_path = find_most_recent_unitree_folder()
        if folder_path is None:
            sys.exit(1)
    
    # Load data
    times, motor_data, joint_names = load_motor_data(folder_path)
    
    # Apply time filtering
    start_time = args.start_time
    end_time = args.end_time
    
    # Find indices for time range
    start_idx = np.searchsorted(times, start_time)
    start_idx = max(0, min(start_idx, len(times) - 1))
    
    if end_time is not None:
        end_idx = np.searchsorted(times, end_time)
        end_idx = max(0, min(end_idx, len(times)))
        print(f"Plotting data from time {times[start_idx]:.2f}s to {times[min(end_idx-1, len(times)-1)]:.2f}s")
    else:
        end_idx = len(times)
        print(f"Plotting data from time {times[start_idx]:.2f}s to end at {times[-1]:.2f}s")
    
    # Slice data
    times = times[start_idx:end_idx]
    for key in motor_data:
        motor_data[key] = motor_data[key][start_idx:end_idx]
    
    # Create plots
    plot_temperatures(times, motor_data, joint_names, folder_path)
    plot_torque_estimates(times, motor_data, joint_names, folder_path)
    plot_motor_states(times, motor_data, joint_names, folder_path)
    plot_temperature_summary(times, motor_data, joint_names, folder_path)
    
    print("Plotting complete!")


if __name__ == "__main__":
    main()