#!/usr/bin/env python3
"""
Script to plot odometry data from CSV files generated by high_level_control.py

Usage:
    python plot_odom.py [--data path_to_csv]

If no path is provided, plots the most recent CSV file from odom_logs.
"""

import argparse
import csv
import glob
import os
import sys
from pathlib import Path
from typing import Optional, Dict

import matplotlib.pyplot as plt
import numpy as np


def find_most_recent_odom_csv() -> Optional[str]:
    """Find the most recent odometry CSV file in odom_logs directory."""
    robot_rl_root = os.environ.get("ROBOT_RL_ROOT", "")
    if not robot_rl_root:
        print("Error: ROBOT_RL_ROOT environment variable not set")
        return None

    odom_logs_dir = os.path.join(robot_rl_root, "odom_logs")
    if not os.path.exists(odom_logs_dir):
        print(f"Error: odom_logs directory not found at {odom_logs_dir}")
        return None

    csv_pattern = os.path.join(odom_logs_dir, "*", "odom_data.csv")
    csv_files = glob.glob(csv_pattern)

    if not csv_files:
        print(f"Error: No odometry CSV files found in {odom_logs_dir}")
        return None

    csv_files.sort(key=os.path.getmtime, reverse=True)
    most_recent = csv_files[0]
    print(f"Using most recent CSV: {most_recent}")
    return most_recent


def load_odom_data(csv_path: str) -> Dict[str, np.ndarray]:
    """Load odometry data from CSV file and return as dictionary."""
    data = {}

    try:
        with open(csv_path, 'r') as f:
            reader = csv.DictReader(f)
            # Initialize lists for each column
            for row in reader:
                if any(v is None for v in row.values()):
                    continue  # Skip incomplete rows (e.g., truncated last line)
                for key, value in row.items():
                    if key not in data:
                        data[key] = []
                    data[key].append(float(value))
    except Exception as e:
        print(f"Error reading CSV file: {e}")
        sys.exit(1)

    # Convert to numpy arrays
    for key in data:
        data[key] = np.array(data[key])

    return data


def slice_data(data: Dict[str, np.ndarray], start_time: float, end_time: Optional[float]) -> Dict[str, np.ndarray]:
    """Slice data to the specified time range."""
    time = data['time']

    start_idx = np.searchsorted(time, start_time)
    start_idx = max(0, min(start_idx, len(time) - 1))

    if end_time is not None:
        end_idx = np.searchsorted(time, end_time)
        end_idx = max(0, min(end_idx, len(time)))
        print(f"Plotting data from time {time[start_idx]:.2f}s to {time[min(end_idx-1, len(time)-1)]:.2f}s")
    else:
        end_idx = len(time)
        print(f"Plotting data from time {time[start_idx]:.2f}s to end at {time[-1]:.2f}s")

    sliced = {}
    for key, arr in data.items():
        sliced[key] = arr[start_idx:end_idx]

    # Adjust time to start from 0
    sliced['time'] = sliced['time'] - start_time

    return sliced


def compute_moving_average(data: np.ndarray, window_size: int) -> tuple[np.ndarray, int]:
    """Compute moving average of data.

    Args:
        data: Input array to smooth.
        window_size: Number of samples for the moving average window.

    Returns:
        Tuple of (smoothed data, offset for alignment with original).
    """
    kernel = np.ones(window_size) / window_size
    smoothed = np.convolve(data, kernel, mode='valid')
    offset = window_size // 2
    return smoothed, offset


def plot_velocity_tracking(data: Dict[str, np.ndarray], save_dir: str, window_size: int = 20) -> None:
    """Create velocity tracking figure with 3 subplots (x, y, yaw rate).

    Args:
        data: Dictionary of odometry data arrays.
        save_dir: Directory to save the plot.
        window_size: Window size for moving average smoothing.
    """
    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    fig.suptitle('Velocity Tracking', fontsize=16)

    time = data['time']

    # Compute moving averages
    x_vel_smooth, offset = compute_moving_average(data['lin_vel_w_x'], window_size)
    y_vel_smooth, _ = compute_moving_average(data['lin_vel_w_y'], window_size)
    yaw_rate_smooth, _ = compute_moving_average(data['ang_vel_w_z'], window_size)
    time_smooth = time[offset:offset + len(x_vel_smooth)]

    # X Velocity
    axes[0].plot(time, data['lin_vel_w_x'], 'b-', linewidth=1, alpha=0.4, label='Actual')
    axes[0].plot(time_smooth, x_vel_smooth, 'b-', linewidth=2, label='Actual (smoothed)')
    if 'x_vel_cmd' in data:
        axes[0].plot(time, data['x_vel_cmd'], 'r--', linewidth=2, label='Commanded')
    axes[0].set_title('X Velocity')
    axes[0].set_xlabel('Time (s)')
    axes[0].set_ylabel('Velocity (m/s)')
    axes[0].set_ylim([4, -1.5])
    axes[0].grid(True, alpha=0.3)
    axes[0].legend()

    # Y Velocity
    axes[1].plot(time, data['lin_vel_w_y'], 'b-', linewidth=1, alpha=0.4, label='Actual')
    axes[1].plot(time_smooth, y_vel_smooth, 'b-', linewidth=2, label='Actual (smoothed)')
    if 'y_cmd' in data:
        axes[1].plot(time, data['y_cmd'], 'r--', linewidth=2, label='Commanded')
    axes[1].set_title('Y Velocity')
    axes[1].set_xlabel('Time (s)')
    axes[1].set_ylabel('Velocity (m/s)')
    axes[1].grid(True, alpha=0.3)
    axes[1].legend()

    # Yaw Rate
    axes[2].plot(time, data['ang_vel_w_z'], 'b-', linewidth=1, alpha=0.4, label='Actual')
    axes[2].plot(time_smooth, yaw_rate_smooth, 'b-', linewidth=2, label='Actual (smoothed)')
    if 'yaw_cmd' in data:
        axes[2].plot(time, data['yaw_cmd'], 'r--', linewidth=2, label='Commanded')
    axes[2].set_title('Yaw Rate')
    axes[2].set_xlabel('Time (s)')
    axes[2].set_ylabel('Angular Velocity (rad/s)')
    axes[2].set_ylim([2, -2])
    axes[2].grid(True, alpha=0.3)
    axes[2].legend()

    plt.tight_layout()

    output_path = os.path.join(save_dir, 'velocity_tracking.png')
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"Saved velocity tracking plot to: {output_path}")


def plot_yaw_y_tracking(data: Dict[str, np.ndarray], save_dir: str) -> None:
    """Create yaw and y tracking figure with 2x2 subplots."""
    fig, axes = plt.subplots(2, 2, figsize=(12, 10))
    fig.suptitle('Yaw and Y Tracking', fontsize=16)

    time = data['time']

    # Yaw: actual vs target
    yaw_actual = np.unwrap(data['yaw_w'])
    yaw_target = np.unwrap(data['yaw_target_w'])
    axes[0, 0].plot(time, yaw_actual, 'b-', linewidth=2, label='Actual')
    axes[0, 0].plot(time, yaw_target, 'r--', linewidth=2, label='Target')
    axes[0, 0].set_title('Yaw Angle')
    axes[0, 0].set_xlabel('Time (s)')
    axes[0, 0].set_ylabel('Yaw (rad)')
    axes[0, 0].grid(True, alpha=0.3)
    axes[0, 0].legend()

    # Yaw error
    axes[0, 1].plot(time, data['yaw_error'], 'orange', linewidth=2)
    axes[0, 1].axhline(y=0.0, color='k', linestyle='-', alpha=0.3)
    axes[0, 1].set_title('Yaw Error')
    axes[0, 1].set_xlabel('Time (s)')
    axes[0, 1].set_ylabel('Error (rad)')
    axes[0, 1].grid(True, alpha=0.3)

    # Y local error
    axes[1, 0].plot(time, data['y_local_error'], 'g-', linewidth=2)
    axes[1, 0].axhline(y=0.0, color='k', linestyle='-', alpha=0.3)
    axes[1, 0].set_title('Y Local Error')
    axes[1, 0].set_xlabel('Time (s)')
    axes[1, 0].set_ylabel('Error (m)')
    axes[1, 0].grid(True, alpha=0.3)

    # Y command
    if 'y_cmd' in data:
        axes[1, 1].plot(time, data['y_cmd'], 'm-', linewidth=2)
        axes[1, 1].axhline(y=0.0, color='k', linestyle='-', alpha=0.3)
        axes[1, 1].set_title('Y Velocity Command')
        axes[1, 1].set_xlabel('Time (s)')
        axes[1, 1].set_ylabel('Velocity (m/s)')
        axes[1, 1].grid(True, alpha=0.3)

    plt.tight_layout()

    output_path = os.path.join(save_dir, 'yaw_y_tracking.png')
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"Saved yaw/y tracking plot to: {output_path}")


def plot_xy_trajectory(data: Dict[str, np.ndarray], save_dir: str) -> None:
    """Create XY position trajectory plot with X and Y position over time."""
    fig, axes = plt.subplots(1, 3, figsize=(18, 6))
    fig.suptitle('Position Tracking', fontsize=16)

    time = data['time']
    robot_x = data['pos_w_x']
    robot_y = data['pos_w_y']

    has_target = 'target_pos_w_x' in data and 'target_pos_w_y' in data
    if has_target:
        target_x = data['target_pos_w_x']
        target_y = data['target_pos_w_y']

    # X Position vs Time
    axes[0].plot(time, robot_x, 'b-', linewidth=2, label='Actual')
    if has_target:
        axes[0].plot(time, target_x, 'r--', linewidth=2, label='Target')
    axes[0].set_title('X Position')
    axes[0].set_xlabel('Time (s)')
    axes[0].set_ylabel('X Position (m)')
    axes[0].grid(True, alpha=0.3)
    axes[0].legend()

    # Y Position vs Time
    axes[1].plot(time, robot_y, 'b-', linewidth=2, label='Actual')
    if has_target:
        axes[1].plot(time, target_y, 'r--', linewidth=2, label='Target')
    axes[1].set_title('Y Position')
    axes[1].set_xlabel('Time (s)')
    axes[1].set_ylabel('Y Position (m)')
    axes[1].grid(True, alpha=0.3)
    axes[1].legend()

    # XY Trajectory
    axes[2].plot(robot_x, robot_y, 'b-', linewidth=2, label='Robot Position')
    axes[2].plot(robot_x[0], robot_y[0], 'go', markersize=10, label='Start')
    axes[2].plot(robot_x[-1], robot_y[-1], 'ro', markersize=10, label='End')
    if has_target:
        axes[2].plot(target_x, target_y, 'r--', linewidth=2, label='Target Position')
        axes[2].plot(target_x[0], target_y[0], 'g^', markersize=10)
        axes[2].plot(target_x[-1], target_y[-1], 'r^', markersize=10)
    axes[2].set_title('XY Trajectory')
    axes[2].set_xlabel('X Position (m)')
    axes[2].set_ylabel('Y Position (m)')
    axes[2].grid(True, alpha=0.3)
    axes[2].legend()
    axes[2].set_aspect('equal')

    plt.tight_layout()

    output_path = os.path.join(save_dir, 'xy_trajectory.png')
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"Saved XY trajectory plot to: {output_path}")


def plot_paper_figure(data: Dict[str, np.ndarray], save_dir: str, window_size: int = 20) -> None:
    """Create a publication-quality figure with LaTeX fonts.

    Generates a 1x3 figure with: X velocity tracking, XY trajectory, and yaw angle tracking.
    Saves as both PNG and PDF.

    Args:
        data: Dictionary of odometry data arrays.
        save_dir: Directory to save the plots.
        window_size: Window size for moving average smoothing.
    """
    # Save original rcParams and set LaTeX configuration
    original_params = {k: plt.rcParams[k] for k in [
        "text.usetex", "font.family", "text.latex.preamble",
        "font.size", "axes.labelsize", "axes.titlesize",
        "xtick.labelsize", "ytick.labelsize", "legend.fontsize",
    ]}
    plt.rcParams.update({
        "text.usetex": True,
        "font.family": "serif",
        "text.latex.preamble": r"\usepackage{amsmath,amsfonts}",
        "font.size": 12,
        "axes.labelsize": 13,
        "axes.titlesize": 14,
        "xtick.labelsize": 11,
        "ytick.labelsize": 11,
        "legend.fontsize": 11,
    })

    fig, axes = plt.subplots(1, 3, figsize=(15, 2.5))
    time = data['time']

    # --- Subplot 1: X Velocity Tracking ---
    x_vel_smooth, offset = compute_moving_average(data['lin_vel_w_x'], window_size)
    time_smooth = time[offset:offset + len(x_vel_smooth)]

    axes[0].plot(time, data['lin_vel_w_x'], color='tab:blue', linewidth=0.8, alpha=0.3)
    axes[0].plot(time_smooth, x_vel_smooth, color='tab:blue', linewidth=2, label=r'Actual')
    if 'x_vel_cmd' in data:
        axes[0].plot(time, data['x_vel_cmd'], color='tab:red', linestyle='--', linewidth=2, label=r'Commanded')
    axes[0].set_xlabel(r'Time (s)')
    axes[0].set_ylabel(r'Velocity ($\mathrm{m/s}$)')
    axes[0].set_title(r'Forward Velocity Tracking')
    axes[0].grid(True, alpha=0.3)
    axes[0].legend()

    # --- Subplot 2: Yaw Angle Tracking ---
    yaw_actual = np.unwrap(data['yaw_w'])
    yaw_target = np.unwrap(data['yaw_target_w'])
    yaw_smooth, yaw_offset = compute_moving_average(yaw_actual, window_size)
    time_yaw_smooth = time[yaw_offset:yaw_offset + len(yaw_smooth)]

    axes[1].plot(time, yaw_actual, color='tab:blue', linewidth=0.8, alpha=0.3)
    axes[1].plot(time_yaw_smooth, yaw_smooth, color='tab:blue', linewidth=2, label=r'Actual')
    axes[1].plot(time, yaw_target, color='tab:red', linestyle='--', linewidth=2, label=r'Desired')
    axes[1].set_xlabel(r'Time (s)')
    axes[1].set_ylabel(r'Yaw Angle (rad)')
    axes[1].set_title(r'Yaw Angle Tracking')
    axes[1].grid(True, alpha=0.3)
    axes[1].legend()

    # --- Subplot 3: XY Trajectory ---
    robot_x = data['pos_w_x']
    robot_y = data['pos_w_y']
    has_target = 'target_pos_w_x' in data and 'target_pos_w_y' in data

    axes[2].plot(robot_x, robot_y, color='tab:blue', linewidth=2, label=r'Actual')
    axes[2].plot(robot_x[0], robot_y[0], 'o', color='tab:green', markersize=8, zorder=5)
    axes[2].plot(robot_x[-1], robot_y[-1], 'o', color='tab:red', markersize=8, zorder=5)
    if has_target:
        target_x = data['target_pos_w_x']
        target_y = data['target_pos_w_y']
        axes[2].plot(target_x, target_y, color='tab:red', linestyle='--', linewidth=2, label=r'Desired')
    axes[2].set_xlabel(r'$x$ Position (m)')
    axes[2].set_ylabel(r'$y$ Position (m)')
    axes[2].set_title(r'$(x,y)$ Trajectory')
    axes[2].grid(True, alpha=0.3)
    axes[2].legend(loc='upper left')
    axes[2].set_aspect('equal')

    # Pad the shorter axis so the plot doesn't get too thin
    x_range = axes[2].get_xlim()[1] - axes[2].get_xlim()[0]
    y_range = axes[2].get_ylim()[1] - axes[2].get_ylim()[0]
    min_aspect_ratio = 0.4  # Shorter axis is at least 40% of longer axis
    if x_range > 0 and y_range > 0:
        if y_range / x_range < min_aspect_ratio:
            y_center = sum(axes[2].get_ylim()) / 2
            new_half = x_range * min_aspect_ratio / 2
            axes[2].set_ylim(y_center - new_half, y_center + new_half)
        elif x_range / y_range < min_aspect_ratio:
            x_center = sum(axes[2].get_xlim()) / 2
            new_half = y_range * min_aspect_ratio / 2
            axes[2].set_xlim(x_center - new_half, x_center + new_half)

    plt.tight_layout()

    # Save as both PNG and SVG
    for ext in ['png', 'svg']:
        output_path = os.path.join(save_dir, f'paper_figure.{ext}')
        plt.savefig(output_path, dpi=300, bbox_inches='tight')
        print(f"Saved paper figure to: {output_path}")
    plt.close()

    # Restore original rcParams
    plt.rcParams.update(original_params)


def main():
    parser = argparse.ArgumentParser(description='Plot odometry data from CSV file')
    parser.add_argument('--data', help='Path to CSV file (if not provided, uses most recent from odom_logs)')
    parser.add_argument('--start-time', type=float, default=0.0, help='Start time for plotting (seconds)')
    parser.add_argument('--end-time', type=float, default=None, help='End time for plotting (seconds)')
    args = parser.parse_args()

    # Determine CSV file to use
    if args.data:
        csv_path = args.data
        if not os.path.exists(csv_path):
            print(f"Error: CSV file not found: {csv_path}")
            sys.exit(1)
    else:
        csv_path = find_most_recent_odom_csv()
        if csv_path is None:
            sys.exit(1)

    # Load data
    print(f"Loading data from: {csv_path}")
    data = load_odom_data(csv_path)

    print(f"Loaded {len(data['time'])} data points spanning {data['time'][-1] - data['time'][0]:.2f} seconds")
    print(f"Available columns: {list(data.keys())}")

    # Slice data to time range
    data = slice_data(data, args.start_time, args.end_time)

    # Determine save directory
    save_dir = os.path.dirname(csv_path)

    # Generate plots
    plot_velocity_tracking(data, save_dir)
    plot_yaw_y_tracking(data, save_dir)
    plot_xy_trajectory(data, save_dir)
    plot_paper_figure(data, save_dir)

    print("Plotting complete!")


if __name__ == "__main__":
    main()
